project_id = "cszwkukwkcrecirbvvee"

[functions.send-webinar-confirmation]
verify_jwt = false

[functions.initialize-certificate-payment]
verify_jwt = false

[functions.verify-certificate-payment]
verify_jwt = false

[functions.initialize-enrollment-payment]
verify_jwt = false

[functions.verify-enrollment-payment]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true